version: '3'
services:
  www:
    image: httpd:alpine
    volumes:
      - "./index.html:/usr/local/apache2/htdocs/index.html:ro"
      - "./gallery.html:/usr/local/apache2/htdocs/gallery.html:ro"
#      - ".:/usr/local/apache2/htdocs"
      - "D:\\projekty\\GTA-V-extractors\\output\\rgb-jpeg:/usr/local/apache2/htdocs/img:ro"
    ports:
      - 8082:80
